stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "mern-app"
  DOCKER_TAG: "$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker save $DOCKER_IMAGE:$DOCKER_TAG | gzip > mern-app.tar.gz
  artifacts:
    paths:
      - mern-app.tar.gz
    expire_in: 1 hour
  only:
    - main

deploy-production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - scp mern-app.tar.gz $DEPLOY_USER@$DEPLOY_HOST:/tmp/
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
        docker load < /tmp/mern-app.tar.gz
        docker stop mern-app || true
        docker rm mern-app || true
        docker run -d \
          --name mern-app \
          --restart unless-stopped \
          -p 80:3000 \
          -e NODE_ENV=production \
          mern-app:$CI_COMMIT_SHORT_SHA
        rm /tmp/mern-app.tar.gz
        echo "Deployment completed!"
      ENDSSH
  environment:
    name: production
    url: http://$DEPLOY_HOST
  only:
    - main
