/**
 * A downloaded report must say the same thing as the emailed one.
 *
 * WHY THIS IS EASY TO GET WRONG
 * One component serves two jobs. In the panel beside the data table it is a
 * thumbnail, and truncating it there is the whole point — the panel was
 * deliberately made small. The Download button prints the SAME component, and
 * there the truncation is a bug: the saved file silently dropped every stat
 * past the fourth and every column past the fifth.
 *
 * That was invisible for as long as no report had more than five columns. The
 * Buy Box report now has twelve and nine stats, so a client who pressed
 * Download got four tiles and five columns, with the entire competitor-pricing
 * half of the report missing — while the emailed PDF, which is generated by
 * completely separate code on the server, carried all of it. Two files, same
 * name, different contents.
 *
 * Nothing else catches this: the server-side PDF tests exercise reportPdf.js,
 * which the download path never touches.
 */
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import ReportDocumentPreview, {
    reportNeedsLandscape,
    WIDE_TABLE_COLUMNS,
} from '../../Components/ESF/ReportDocumentPreview.jsx';

/** A Buy Box report at full width: nine stats, twelve columns. */
const report = {
    key: 'buybox',
    name: 'Weekly Buybox Report',
    cadence: 'WEEKLY',
    available: true,
    date: '20 Sep 2026',
    summary: {
        headline: '1 of 2 ASINs currently hold the Buy Box',
        stats: [
            { label: 'ASINs tracked', value: 2 },
            { label: 'Winning', value: 1 },
            { label: 'Losing', value: 1 },
            { label: 'Below 50%', value: 0 },
            { label: 'Buy Box ownership', value: 50, format: 'percent' },
            { label: 'Snapshots on file', value: 8 },
            { label: 'Suppressed listings', value: 0 },
            { label: 'Priced above Buy Box', value: 1 },
            { label: 'Widest price gap', value: 4.99, format: 'money' },
        ],
        columns: [
            { key: 'sku', label: 'SKU' },
            { key: 'asin', label: 'ASIN' },
            { key: 'ourPrice', label: 'Our price', format: 'money' },
            { key: 'competingPrice', label: 'Buy Box price', format: 'money' },
            { key: 'priceGap', label: 'Gap', format: 'money' },
            { key: 'pricingFlag', label: 'Pricing' },
            { key: 'competingSeller', label: 'Buy Box seller' },
            { key: 'status', label: 'Status' },
            { key: 'ownership', label: 'Buy Box %', format: 'percent' },
            { key: 'periodsLosing', label: 'Snapshots losing', format: 'number' },
            { key: 'sessions', label: 'Sessions', format: 'number' },
            { key: 'unitsOrdered', label: 'Units', format: 'number' },
        ],
        rows: [{
            sku: 'SKU-1', asin: 'B0CZ8HJ4KQ', ourPrice: 22.49, competingPrice: 17.5,
            priceGap: 4.99, pricingFlag: 'Priced above', competingSeller: 'A1B2C3D4E5F6G',
            status: 'Losing', ownership: 0, periodsLosing: 3, sessions: 120, unitsOrdered: 4,
        }],
    },
    highlights: [],
    caveats: [],
};

const props = { report, marketplace: { country: 'US' }, currency: '$' };

describe('ReportDocumentPreview', () => {
    describe('the panel thumbnail', () => {
        it('stays truncated, which is what the small panel is for', () => {
            render(<ReportDocumentPreview {...props} />);

            expect(screen.getByText('ASINs tracked')).toBeInTheDocument();
            expect(screen.getByText('SKU')).toBeInTheDocument();
            // Past the cut.
            expect(screen.queryByText('Widest price gap')).not.toBeInTheDocument();
            expect(screen.queryByText('Buy Box seller')).not.toBeInTheDocument();
        });
    });

    describe('the copy that gets downloaded', () => {
        it('carries every stat, not just the first four', () => {
            render(<ReportDocumentPreview {...props} full />);

            // getAllByText, not getByText: "Losing" is both a stat label and
            // a value in the Status column, and a uniqueness assumption here
            // would fail for a reason that has nothing to do with the cut.
            for (const stat of report.summary.stats) {
                expect(screen.getAllByText(stat.label).length).toBeGreaterThan(0);
            }
        });

        it('carries every column, including all of the competitor pricing', () => {
            render(<ReportDocumentPreview {...props} full />);

            for (const column of report.summary.columns) {
                expect(screen.getByText(column.label)).toBeInTheDocument();
            }
        });

        it('prints the price cells to the cent, as the emailed PDF does', () => {
            render(<ReportDocumentPreview {...props} full />);

            // $22 / $18 / $5 would be three numbers that no longer reconcile.
            expect(screen.getByText('$22.49')).toBeInTheDocument();
            expect(screen.getByText('$17.50')).toBeInTheDocument();
            // Twice over: the Widest price gap tile and the row's own cell.
            // Both go through the same format, and both must keep the cents.
            expect(screen.getAllByText('$4.99')).toHaveLength(2);
        });

        it('puts the minus before the symbol on a negative gap', () => {
            // Losing while priced BELOW the Buy Box is the good case, and must
            // not render as "$-5.00".
            const cheaper = {
                ...report,
                summary: {
                    ...report.summary,
                    rows: [{ ...report.summary.rows[0], priceGap: -5, pricingFlag: 'Priced below' }],
                },
            };
            render(<ReportDocumentPreview {...props} report={cheaper} full />);

            expect(screen.getByText('-$5.00')).toBeInTheDocument();
        });

        it('does not hide columns behind a scrollbar that paper does not have', () => {
            // The panel wraps its table in overflow-x:auto, which is right on
            // screen and fatal on paper: printing CLIPS the overflow, so the
            // right-hand columns would be absent from the saved file with
            // nothing to indicate they were ever there.
            const { container } = render(<ReportDocumentPreview {...props} full />);
            const scrollers = [...container.querySelectorAll('div')]
                .filter((node) => node.style.overflowX === 'auto');
            expect(scrollers).toHaveLength(0);
        });

        it('lets headers wrap, since nowrap sets a floor under the table width', () => {
            const { container } = render(<ReportDocumentPreview {...props} full />);
            const headers = [...container.querySelectorAll('th')];
            expect(headers.length).toBeGreaterThan(0);
            expect(headers.every((th) => th.style.whiteSpace === 'normal')).toBe(true);
        });

        it('keeps the scrollbar and the nowrap for the on-screen panel', () => {
            // The compact panel is unchanged: this fix is for the printed copy.
            const { container } = render(<ReportDocumentPreview {...props} />);
            expect([...container.querySelectorAll('div')]
                .filter((node) => node.style.overflowX === 'auto').length).toBeGreaterThan(0);
            expect([...container.querySelectorAll('th')]
                .every((th) => th.style.whiteSpace === 'nowrap')).toBe(true);
        });

        it('shows an em dash where a gap could not be computed', () => {
            // Null is "not priced" and 0 is "matched"; rendering them alike
            // would turn a gap in our data into a claim about the listing.
            const unpriced = {
                ...report,
                summary: {
                    ...report.summary,
                    rows: [{
                        ...report.summary.rows[0],
                        competingPrice: null, priceGap: null, pricingFlag: '—', competingSeller: '—',
                    }],
                },
            };
            render(<ReportDocumentPreview {...props} report={unpriced} full />);

            expect(screen.queryByText('$0.00')).not.toBeInTheDocument();
            expect(screen.getAllByText('—').length).toBeGreaterThan(0);
        });
    });
});

describe('reportNeedsLandscape', () => {
    it('turns the page for this twelve-column report', () => {
        expect(reportNeedsLandscape(report)).toBe(true);
    });

    it('leaves every report that already fitted in portrait', () => {
        const narrow = (count) => ({
            summary: {
                columns: Array.from({ length: count }, (_, i) => ({ key: `k${i}`, label: `L${i}` })),
            },
        });
        expect(reportNeedsLandscape(narrow(WIDE_TABLE_COLUMNS))).toBe(false);
        expect(reportNeedsLandscape(narrow(4))).toBe(false);
    });

    it('counts a wide SECONDARY table too', () => {
        // The Buy Box report's suppressed-listings table shares the page; a
        // narrow primary must not leave it running off the edge.
        expect(reportNeedsLandscape({
            summary: {
                columns: [{ key: 'a', label: 'A' }],
                secondaryTable: {
                    columns: Array.from({ length: 12 }, (_, i) => ({ key: `k${i}`, label: `L${i}` })),
                },
            },
        })).toBe(true);
    });

    it('agrees with the server threshold, so the two files break alike', () => {
        // LANDSCAPE_COLUMN_THRESHOLD in server/Services/Reports/reportPdf.js.
        expect(WIDE_TABLE_COLUMNS).toBe(9);
    });

    it('survives a report with no summary', () => {
        expect(reportNeedsLandscape(undefined)).toBe(false);
        expect(reportNeedsLandscape({})).toBe(false);
    });
});
