/**
 * ZohoTaskSummaryService.js
 *
 * Turns a Zoho task's comment thread into a short, DATE-WISE progress update
 * the CLIENT can read, so the Status page shows what happened on each day
 * instead of the agency's raw internal chatter — and instead of one blended
 * paragraph that flattens a week of work into "work is progressing."
 *
 * Mirrors the established pattern in this codebase (TopOpportunitiesService and
 * the engine narrators): gpt-4o-mini, lazy client, and — the important part —
 * the feature NEVER hard-fails on the LLM. No key, a bad response, a timeout:
 * every path falls back to a deterministic summary built from the thread
 * itself, because a task row with an empty detail panel is worse than a plain
 * one.
 *
 * ── DATES ARE NEVER WRITTEN BY THE MODEL ──
 * waitingOnClient.since has always been computed server-side from the thread,
 * never asked of the model, because an LLM is unreliable with dates. The same
 * rule now governs the whole summary: the model is given comments pre-grouped
 * into calendar-day blocks labelled "Day 1", "Day 2"... and is asked to return
 * exactly one prose entry per block, IN THAT ORDER. The real date for each
 * entry comes from our own grouping, matched by POSITION — the model never
 * emits a date string that could be wrong, copied badly, or silently drift
 * from the data it was actually shown.
 *
 * COST
 * Summarising runs inside the nightly sync, never on page load. It is also
 * skipped entirely when a thread has not changed since the last summary — the
 * linked project has 76 tasks whose threads mostly sit still for weeks, so
 * re-summarising all of them every night would be ~27k paid calls a year to
 * regenerate identical text. `sourceHash` is what makes that skip safe, and it
 * is unaffected by the day-wise rewrite — it still hashes the whole thread.
 */

const crypto = require('crypto');
const OpenAI = require('openai');
const logger = require('../../utils/Logger.js');

// Same model as the other narrators. The prompt is small and runs nightly, so
// upgrading is a one-line env change.
const MODEL = process.env.ZOHO_TASK_SUMMARY_MODEL || 'gpt-4o-mini';

/**
 * Up to MAX_DAYS_IN_SUMMARY entries, each 1-2 short sentences, plus the team
 * and the (usually short) pending-ask object. 320 was sized for one blended
 * paragraph; a day-wise reply with up to six entries needs more headroom.
 */
const MAX_OUTPUT_TOKENS = 500;

/**
 * Bumped whenever SYSTEM_PROMPT or the output shape changes.
 *
 * Without it the sourceHash cache would happily serve summaries generated by an
 * older prompt forever, because the THREAD has not changed — only our reading of
 * it has. Reuse requires both the hash and this version to match.
 *
 * 5 — the day-wise rewrite. The output contract changed from one blended
 *     "summary" string to a "days" array matched positionally to real calendar
 *     days, so every summary ever stored under version 4 is stale by definition
 *     and must regenerate once.
 */
const PROMPT_VERSION = 5;

/**
 * Teams the work can be attributed to. A FIXED vocabulary, because the client sees
 * this verbatim and "Adverts squad" one night and "PPC team" the next reads as
 * disorganised. Anything unrecognised falls back to the generic label.
 */
const TEAMS = [
    'Advertising team',
    'Content team',
    'Design team',
    'Photography team',
    'SEO team',
    'Marketplace team',
    // Seller Central operations and compliance are the bulk of the work on a real
    // project — 52 of 76 tasks on the live one — and they are not the same craft as
    // client communication. Filing them all under "Account management" made that
    // column almost useless AND misdescribed the work: to a client, "account
    // management" means their account manager, not a pesticide registration.
    'Seller Central team',
    'Compliance team',
    'Account management',
];
/**
 * No team could be determined. Null rather than a placeholder label: inventing
 * "Your eStore Factory team" put branding in a column whose job is to name a craft,
 * and it read as a team that does not exist. The UI shows a dash instead.
 */
const DEFAULT_TEAM = null;

/**
 * Which team a task belongs to, without a model.
 *
 * Order matters: "keyword" appears in both advertising and SEO work, and a task that
 * mentions bids is an advertising one, so the narrower rules are tested first.
 */
const TEAM_RULES = [
    // Stems, not whole words: "photo" has to match "Photography", and "advertis" has
    // to match "Advertising". A trailing \b would fail both. "a+" is anchored only at
    // the front because "+" is not a word character, so \b after it never matches.
    //
    // Order is significant throughout — the narrower craft wins. Compliance before
    // Seller Central (a trademark filing is compliance, not account ops), Seller
    // Central before Content ("product creation" is an ops task, not copywriting),
    // and Advertising before SEO because both talk about keywords.
    [/\b(epa|pesticide|trademark|compliance|certificat\w*|registration|regulat\w*|legal|patent)\b/i, 'Compliance team'],
    [/\b(ppc|acos|bids?|budget|campaign|advertis\w*|sponsored)\b/i, 'Advertising team'],
    [/\b(photo\w*|image\w*|lifestyle|shoot)\b/i, 'Photography team'],
    [/(\ba\+|\b(ebc|design\w*|creative|graphic\w*|brand story|storefront|infographic)\b)/i, 'Design team'],
    [/\b(seller central|verification|verified|brand registry|restock|inventory|suspend\w*|reinstat\w*|appeal|account health|pricing|shipping|return policy|product creation)\b/i, 'Seller Central team'],
    [/\b(seo|ranking|search terms?|backend keywords?)\b/i, 'SEO team'],
    [/\b(walmart|etsy|ebay|shopify|marketplace)\b/i, 'Marketplace team'],
    [/\b(communication\w*|onboarding|sow|invoice\w*|call|meeting)\b/i, 'Account management'],
    [/\b(content|copy\w*|bullets?|titles?|descriptions?|listings?|keywords?|details?)\b/i, 'Content team'],
];

const deterministicTeam = (task = {}) => {
    /*
     * The NAME decides; the tasklist is only a fallback hint.
     *
     * Matching both together is wrong because a tasklist name leaks into every task
     * inside it — the live project has a list called "Seller Central Task", which
     * made "SEO content" and "Internal Communication" both come out as Seller
     * Central work. A list groups tasks administratively; the name says what the
     * work actually is.
     */
    const match = (text) => {
        if (!text) return null;
        for (const [pattern, team] of TEAM_RULES) {
            if (pattern.test(text)) return team;
        }
        return null;
    };

    return match(task.name) || match(task.tasklist) || DEFAULT_TEAM;
};

const sanitiseTeam = (raw) => (TEAMS.includes(raw) ? raw : null);

/**
 * Remove every staff name we know about from client-facing text.
 *
 * This is the GUARANTEE, and the prompt is only the first line of defence: a model
 * told not to name people still will occasionally, and the client must never see who
 * inside the agency is doing what.
 *
 * Full names go first so "Priya Sharma" does not become "the team Sharma". Individual
 * parts are only redacted at 3+ characters — short fragments like "Jo" or "Li" would
 * match inside ordinary words and mangle readable text.
 */
/**
 * Shared role accounts, not people.
 *
 * This portal has a Zoho user literally called "Support". Redacting it would rewrite
 * "Contact Amazon support" as "Contact Amazon the team" — damage to ordinary text for
 * no privacy gain, since a role mailbox identifies nobody. Names of real individuals
 * are never on this list.
 */
const ROLE_ACCOUNT_WORDS = new Set([
    'support', 'team', 'admin', 'sales', 'info', 'help', 'service', 'services',
    'design', 'content', 'media', 'marketing', 'accounts', 'billing', 'operations',
    'office', 'contact', 'hello', 'noreply',
]);

const redactNames = (text, names = []) => {
    if (!text) return text;

    const escape = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const parts = new Set();

    for (const name of names) {
        const full = String(name || '').trim();
        if (full.length < 3) continue;
        if (!ROLE_ACCOUNT_WORDS.has(full.toLowerCase())) parts.add(full);
        for (const piece of full.split(/\s+/)) {
            if (piece.length >= 3 && !ROLE_ACCOUNT_WORDS.has(piece.toLowerCase())) parts.add(piece);
        }
    }

    // Longest first, so full names are consumed before their own parts.
    const ordered = [...parts].sort((a, b) => b.length - a.length);

    let out = text;
    for (const part of ordered) {
        // Optional leading @ (zohoRichText renders mentions as "@Name") and an
        // optional possessive, so "@Priya's" does not leave "'s" behind.
        out = out.replace(new RegExp(`@?\\b${escape(part)}\\b(?:'s|’s)?`, 'gi'), 'the team');
    }

    // Collapse what redaction can pile up: "the team and the team", stray double
    // spaces, and a leading ", ".
    return out
        .replace(/\bthe team(?:[,\s]+(?:and\s+)?the team)+/gi, 'the team')
        .replace(/\s{2,}/g, ' ')
        .replace(/\s+([,.;:])/g, '$1')
        .trim();
};

/** What a client can be asked for. Kept small so the UI can icon/group them. */
const ASK_KINDS = ['photos', 'video', 'approval', 'information', 'content', 'access', 'other'];

// Input bounds. Long threads are the exception (the live max is 17 comments),
// but one runaway thread should not dominate the nightly token spend.
const MAX_COMMENTS_IN_PROMPT = 20;

/**
 * How many distinct calendar days of activity are shown. More than this and the
 * detail panel stops being a quick read — a task that has had comments on ten
 * different days shows its six most recent and says how many are collapsed,
 * the same way the old single-paragraph version said "(N earlier updates)".
 */
const MAX_DAYS_IN_SUMMARY = 6;

/**
 * A character ceiling PER DAY, replacing the old single ceiling over the whole
 * prompt.
 *
 * A single pathological day (one comment pasted 200 times, say) must not blow
 * the token budget — but it must also not be allowed to swallow the day
 * headers that come after it. Capping per day keeps the day COUNT exact
 * (always equal to what the model is told to expect) no matter how lopsided
 * the content is; a single global tail-truncation could silently delete whole
 * day blocks from the front and break the day-for-day positional contract the
 * rest of this file depends on.
 */
const MAX_CHARS_PER_DAY = 1200;

// Below this there is nothing to summarise — the deterministic path reads
// better than asking a model to pad one line into three.
const MIN_COMMENTS_FOR_AI = 2;

let openaiClient = null;

function getOpenAIClient() {
    if (openaiClient) return openaiClient;

    const apiKey = process.env.OPENAPI_KEY;
    if (!apiKey) {
        // Not thrown — callers degrade to the deterministic summary instead.
        logger.warn('[ZohoTaskSummary] OPENAPI_KEY is not set; using deterministic summaries');
        return null;
    }
    try {
        openaiClient = new OpenAI({ apiKey });
        return openaiClient;
    } catch (err) {
        logger.error('[ZohoTaskSummary] Failed to initialize OpenAI client', { message: err.message });
        return null;
    }
}

/**
 * Identity of a thread's CONTENT, so an unchanged thread is never re-summarised.
 * Deliberately covers the text and author of every comment: an edited comment
 * changes the hash, a re-fetch that returns the same thread does not.
 *
 * Still hashes the FULL thread, unaffected by the day-wise rewrite below — the
 * cache question is still exactly "has anything in this thread changed", not
 * "has anything in the shown window changed".
 */
const hashThread = (comments = []) => crypto
    .createHash('sha256')
    .update(comments.map((c) => `${c.id || c.commentId || ''}:${c.authorName || ''}:${c.content || ''}`).join('\x00'))
    .digest('hex');

/**
 * YYYY-MM-DD in UTC — the calendar day a comment belongs to.
 *
 * UTC, not the server's local zone, so this never depends on which host it
 * happens to run on. It is a narrative label ("shown on this day in the
 * story"), not a precise timestamp compared against anything else on the
 * page — a comment arriving right at a UTC day boundary can read one day
 * either side of what a reader in another timezone would call it, which is an
 * acceptable imprecision for a label and not worth making this stateful.
 */
const dayKey = (value) => {
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
};

const DAY_LABEL_FORMAT = new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', timeZone: 'UTC' });

/** "2026-09-01" -> "1 Sept". A key of null (no valid date) reads as "Undated". */
const formatDayLabel = (key) => (key ? DAY_LABEL_FORMAT.format(new Date(`${key}T00:00:00.000Z`)) : 'Undated');

/**
 * Group comments into calendar-day buckets, OLDEST FIRST.
 *
 * A missing or unparseable createdAt goes in its own 'undated' bucket, sorted
 * after every real date, rather than being silently dropped — Zoho always
 * timestamps comments in practice, but nothing here should crash on a record
 * that does not.
 */
const groupByDay = (comments) => {
    const byKey = new Map();
    for (const c of comments) {
        const key = dayKey(c.createdAt) || 'undated';
        if (!byKey.has(key)) byKey.set(key, []);
        byKey.get(key).push(c);
    }
    const keys = [...byKey.keys()].sort((a, b) => {
        if (a === 'undated') return 1;
        if (b === 'undated') return -1;
        return a.localeCompare(b);
    });
    return keys.map((key) => ({ key, comments: byKey.get(key) }));
};

/**
 * The most recent MAX_DAYS_IN_SUMMARY day-groups, and how many earlier ones
 * were left out. Shared by the prompt builder and the deterministic fallback
 * so the two paths can never disagree about which days are "shown".
 */
const windowDays = (groups) => {
    const shown = groups.slice(-MAX_DAYS_IN_SUMMARY);
    return { shown, earlierCount: groups.length - shown.length };
};

const SYSTEM_PROMPT = `You read an agency's internal task discussion, already split into calendar-day blocks labelled "Day 1", "Day 2"... in chronological order, and produce two things for the CLIENT whose account the work is on.

Return JSON only, exactly this shape:
{
  "days": ["<1-2 short sentences for Day 1, or \\"\\" if that day has nothing worth reporting>", "<Day 2>", "..."],
  "team": "Advertising team|Content team|Design team|Photography team|SEO team|Marketplace team|Account management",
  "waitingOnClient": null | { "ask": "one short sentence", "kind": "photos|video|approval|information|content|access|other" }
}

"days" MUST have exactly one entry per day block given, IN THE SAME ORDER. Do not merge two days into one entry, do not skip a day, do not add a day that was not given, and do not reorder them.

NEVER write a date, weekday or relative time word ("today", "yesterday", "this week") into any entry — the date for each entry is added separately from your own day blocks, by position. Writing one yourself risks it being wrong or inconsistent with the real date.

SUMMARY RULES (apply to every entry in "days"):
1. Report ONLY what that day's discussion actually says. Never invent progress, numbers or outcomes, and never pull in detail from a different day's block to pad a thin one.
2. Write for the client, about their account. Say what was done, what was happening, or what was raised that day — only where that day's block states it.
3. Do not address anyone by name in the second person. Refer to the agency as "we".
4. NEVER name any individual. Not agency staff, not the people in the discussion, not in any form — no first names, surnames or @mentions. Say "we" or "the team". This is absolute: the client must never learn which individual is doing what.
5. Never include: internal pricing or margin discussion, complaints about the client, staff performance remarks, credentials, or links.
6. If a day's block is only acknowledgements ("ok", "done", "thanks") with no substance, return "" for that day's entry — do not pad it into a sentence.
7. Never use the words "summary", "thread", "comment", "day" or "task" to describe what you are doing. Just state the update.

waitingOnClient RULES — be strict, a false alarm is worse than a miss:
8. Set it ONLY when the discussion shows the agency is blocked waiting for something the CLIENT must supply or decide, as of the LAST day block given.
9. It must be something the client can act on: files, photos, video, written content, an approval or decision, factual information, or access to an account.
10. Set it to null when: the work is simply in progress, we are waiting on Amazon or on another agency team, or the request was already fulfilled later in the discussion.
11. Address the ask to the client in the second person: "Send four lifestyle photos of the espresso tamper", "Approve the Q4 ad budget".
12. Never invent an ask to fill the field. Null is the correct and common answer.

team RULES:
13. Pick the one team from the list above whose craft the work belongs to, judged across the whole discussion, by the work, not the wording.
13a. "Seller Central team" is Amazon account operations: verification, brand registry, restock and inventory, pricing, shipping and return policy, suspensions and reinstatements, creating products.
13b. "Compliance team" is regulatory and legal work: EPA and pesticide rules, trademarks and patents, certificates, state registrations.
13c. "Account management" is ONLY client-facing coordination: calls, status updates, scoping, invoicing. Do not use it as a catch-all — if the work has a craft, name that craft.
14. The ask in waitingOnClient must also name no individual.`;

/**
 * Build one day block's own lines, tail-truncated to MAX_CHARS_PER_DAY.
 *
 * The tail, not the head, is kept — the latest comment within a day is the one
 * that matters most if the day itself has to be trimmed, the same "keep the
 * end" rule the old single-block version used over the whole thread.
 */
const dayBlockLines = (dayComments) => {
    let text = dayComments
        .map((c) => `${c.authorName || 'Team'}: ${(c.content || '').trim()}`)
        .filter((line) => line.length > 0)
        .join('\n');
    if (text.length > MAX_CHARS_PER_DAY) {
        text = `…\n${text.slice(text.length - MAX_CHARS_PER_DAY)}`;
    }
    return text;
};

/**
 * Trim a thread to what is worth sending, group it by day, and build the
 * day-blocked prompt body.
 *
 * @returns {{ text: string, days: Array<{ key: string, label: string }> }}
 *   `days` is the list the model must return exactly one entry per, in order —
 *   the real date for entry i is `days[i].label`, supplied by us, never by the
 *   model.
 */
const buildPromptText = (comments) => {
    const recent = comments.slice(-MAX_COMMENTS_IN_PROMPT);
    const groups = groupByDay(recent);
    const { shown } = windowDays(groups);

    const text = shown
        .map((group, i) => `Day ${i + 1} (${formatDayLabel(group.key === 'undated' ? null : group.key)}):\n${dayBlockLines(group.comments)}`)
        .join('\n\n');

    return {
        text,
        days: shown.map((group) => ({ key: group.key, label: formatDayLabel(group.key === 'undated' ? null : group.key) })),
    };
};

/** A line that is only @mentions and punctuation carries no update. */
const isMentionOnly = (line) => !line.replace(/@[\w .'-]+/g, '').replace(/[\s,;:&/-]+/g, '').length;

/**
 * A line that is only a bare acknowledgement — "ok", "thanks!", "done" — with
 * no update of its own. The AI path's rule 6 already treats a day that is
 * only this kind of line as having nothing worth reporting; the deterministic
 * fallback is kept consistent with it here, so the two paths cannot disagree
 * about what counts as "no detail" on the same input.
 */
const ACK_PHRASE = '(?:ok(?:ay)?|done|sure|noted|perfect|great|sounds good|got it|no problem|yes|yep|thanks?(?:\\s+(?:you|a lot))?|thank you)';
// One ack phrase, or several joined by a comma/"and"/whitespace — "ok thanks",
// "sure, no problem" are both single acknowledgements in practice, not two
// separate pieces of information.
const ACK_ONLY_RE = new RegExp(`^${ACK_PHRASE}(?:\\s*[,.!]*\\s*(?:and\\s+)?${ACK_PHRASE})*[.!]*$`, 'i');
const isNoiseOnly = (line) => isMentionOnly(line) || ACK_ONLY_RE.test(line.trim());

/**
 * The first genuinely substantive line in one day's comments, scanning from
 * the LATEST comment of that day backward — mirrors the original single-
 * thread version's "skip the leading @mentions line" behaviour, just scoped
 * to one day instead of the whole thread, and willing to look past a trailing
 * mention-only or ack-only line to the real update earlier the same day.
 */
const substantiveLineFor = (dayComments) => {
    for (let i = dayComments.length - 1; i >= 0; i -= 1) {
        const content = (dayComments[i].content || '').trim();
        if (!content) continue;
        const lines = content.split('\n').map((l) => l.trim()).filter(Boolean);
        const line = lines.find((l) => !isNoiseOnly(l));
        if (line) return line;
    }
    return null;
};

const CLIP_AT = 220;
const clip = (line) => (line.length > CLIP_AT ? `${line.slice(0, CLIP_AT - 1).trimEnd()}…` : line);

/**
 * The no-LLM answer. Used when the key is missing, the call fails, or the
 * thread is too thin to be worth a call.
 *
 * Day-wise, like the AI path, for the same reason the rest of this file is:
 * a reader comparing two nights where the model happened to be down and
 * nights it was not should see the same SHAPE of update, not a demotion to a
 * single blended line.
 *
 * No longer takes a `team` parameter. The old version named the team inline
 * ("Latest update from the Content team: ...") because that was the only
 * place a reader could learn which craft was handling the work. The Status
 * page now shows `task.team` as its own column on every row, so repeating it
 * on every dated line would be redundant rather than useful.
 */
const deterministicSummary = (comments) => {
    // Every author across the WHOLE thread, not just the day being rendered —
    // a day's substantive line can still mention someone who only commented on
    // a different day (replying to, or being asked about, that person).
    // Scoping this to the day's own authors was a real gap caught in review:
    // it would have let such a name through un-redacted.
    const names = comments.map((c) => c.authorName).filter(Boolean);

    const groups = groupByDay(comments.filter((c) => (c.content || '').trim()));
    if (!groups.length) return 'No updates on this task yet.';

    const { shown, earlierCount } = windowDays(groups);
    const lines = [];
    for (const group of shown) {
        const line = substantiveLineFor(group.comments);
        if (!line) continue;
        const label = formatDayLabel(group.key === 'undated' ? null : group.key);
        lines.push(`${label}: ${redactNames(clip(line), names)}`);
    }

    if (!lines.length) return 'No detailed updates on this task yet.';
    if (earlierCount > 0) {
        lines.push(`${earlierCount} earlier day${earlierCount === 1 ? '' : 's'} with activity not shown.`);
    }
    return lines.join('\n');
};

/** The two fixed phrases meaning "nothing to report" — see deterministicSummary. */
const NO_UPDATE_PHRASES = new Set(['No updates on this task yet.', 'No detailed updates on this task yet.']);

/** Matches the trailing "(N) earlier day(s)..." note, never itself an update. */
const EARLIER_DAYS_NOTE_RE = /^\d+ earlier days? with activity not shown\.$/;

/**
 * The single most recent dated line from a day-wise summary — for a surface
 * that only has room for one line, rather than the full history.
 *
 * ── WHY THIS EXISTS ──
 * `commentSummary.text` is now several dated lines, and the Status page's
 * detail panel is the one place built for that (it already renders with
 * `white-space: pre-line`, so it needed no change at all). The Client
 * Dashboard's "What we're working on" widget is a different surface — its own
 * doc-comment calls it "One line of what we're working on" and clamps to two
 * visual lines with no newline handling — so handing it the same multi-line
 * text would collapse into one run-on sentence and get cut off mid-word.
 *
 * Day order is oldest-first, so the most recent entry is simply the LAST
 * line — with the trailing "(N) earlier days..." note excluded, since
 * showing THAT instead of a real update would be exactly backwards for a
 * "what's happening now" glance.
 *
 * @returns {string|null} null for the two "nothing to report" phrases, so a
 *   caller can render its own empty state instead of printing one of them as
 *   if it were an update line.
 */
const latestLine = (text) => {
    if (!text || NO_UPDATE_PHRASES.has(text)) return null;
    const lines = text.split('\n').filter((l) => !EARLIER_DAYS_NOTE_RE.test(l));
    return lines.length ? lines[lines.length - 1] : null;
};

/** Keep only an ask the model returned in the agreed shape. */
const sanitiseAsk = (raw) => {
    if (!raw || typeof raw !== 'object') return null;
    const ask = typeof raw.ask === 'string' ? raw.ask.trim() : '';
    if (!ask || ask.length > 300) return null;
    const kind = ASK_KINDS.includes(raw.kind) ? raw.kind : 'other';
    return { ask, kind };
};

/**
 * Summarise one task's comment thread, and detect anything it says the agency
 * is waiting on the client for.
 *
 * @param {Object}  task              { name, comments: [{id, content, authorName, createdAt}] }
 * @param {Object}  [options]
 * @param {string}  [options.previousHash]     hash of the thread the stored result came from
 * @param {string}  [options.previousText]     the stored summary, reused when nothing changed
 * @param {number}  [options.previousVersion]  prompt version that produced the stored result
 * @param {Object}  [options.previousAsk]      the stored waitingOnClient, reused alongside it
 */
const summariseTask = async (task, {
    previousHash = null, previousText = null, previousVersion = null, previousAsk = null,
    previousTeam = null,
} = {}) => {
    const comments = task.comments || [];
    const sourceHash = hashThread(comments);
    const fallbackTeam = deterministicTeam(task);

    /**
     * Every staff name this task can possibly expose. Gathered from the task record
     * as well as the thread, because an owner may never have commented and would
     * otherwise slip through the redaction below.
     */
    const staffNames = [
        ...(task.ownerNames || []),
        task.createdByName,
        task.updatedByName,
        ...comments.map((c) => c.authorName),
    ].filter(Boolean);

    const base = {
        sourceHash,
        commentCount: comments.length,
        model: null,
        reused: false,
        promptVersion: PROMPT_VERSION,
        waitingOnClient: null,
        team: fallbackTeam,
    };

    // Reuse only when the thread AND our reading of it are both unchanged. A
    // prompt change must re-run even though the source is identical.
    if (previousHash && previousText && previousHash === sourceHash && previousVersion === PROMPT_VERSION) {
        return {
            ...base,
            text: previousText,
            waitingOnClient: previousAsk || null,
            team: previousTeam || fallbackTeam,
            generatedBy: 'reused',
            reused: true,
        };
    }

    if (comments.length < MIN_COMMENTS_FOR_AI) {
        return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
    }

    const client = getOpenAIClient();
    if (!client) {
        return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
    }

    const { text: promptBody, days: expectedDays } = buildPromptText(comments);
    if (expectedDays.length === 0) {
        // Defensive: every comment was unparseable-date AND somehow still here.
        // MIN_COMMENTS_FOR_AI makes this unreachable in practice.
        return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
    }

    try {
        const completion = await client.chat.completions.create({
            model: MODEL,
            temperature: 0.2,
            max_tokens: MAX_OUTPUT_TOKENS,
            response_format: { type: 'json_object' },
            messages: [
                { role: 'system', content: SYSTEM_PROMPT },
                {
                    role: 'user',
                    content: `Task: ${task.name || 'Untitled'}\n\nDiscussion:\n${promptBody}`,
                },
            ],
        });

        const content = completion?.choices?.[0]?.message?.content;
        if (!content || !content.trim()) {
            logger.warn('[ZohoTaskSummary] Model returned empty content', { task: task.name });
            return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
        }

        let parsed;
        try {
            parsed = JSON.parse(content);
        } catch (parseError) {
            logger.warn('[ZohoTaskSummary] Model returned unparseable JSON', { message: parseError.message });
            return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
        }

        /**
         * The core invariant: one entry per day block, in order. Anything else —
         * missing, extra, or not even an array — means the positional mapping
         * to real dates cannot be trusted, so this is treated exactly like
         * unparseable JSON: full fallback, not a partial salvage.
         */
        const rawDays = Array.isArray(parsed.days) ? parsed.days : null;
        if (!rawDays || rawDays.length !== expectedDays.length) {
            logger.warn('[ZohoTaskSummary] Model returned the wrong number of day entries', {
                task: task.name, expected: expectedDays.length, got: rawDays?.length ?? null,
            });
            return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
        }

        // Redaction runs over the model's output regardless of what the prompt asked
        // for. Rule 4 is an instruction; this is the guarantee.
        const lines = [];
        for (let i = 0; i < expectedDays.length; i += 1) {
            const raw = typeof rawDays[i] === 'string' ? rawDays[i].trim() : '';
            if (!raw) continue; // the model said this day had nothing worth reporting
            lines.push(`${expectedDays[i].label}: ${redactNames(raw, staffNames)}`);
        }
        const text = lines.length ? lines.join('\n') : 'No detailed updates on this task yet.';

        const ask = sanitiseAsk(parsed.waitingOnClient);

        return {
            ...base,
            text,
            waitingOnClient: ask ? { ...ask, ask: redactNames(ask.ask, staffNames) } : null,
            team: sanitiseTeam(parsed.team) || fallbackTeam,
            generatedBy: 'ai',
            model: MODEL,
        };
    } catch (error) {
        logger.error('[ZohoTaskSummary] OpenAI call failed', { model: MODEL, message: error.message });
        return { ...base, text: deterministicSummary(comments), generatedBy: 'fallback' };
    }
};

module.exports = {
    summariseTask,
    hashThread,
    deterministicSummary,
    deterministicTeam,
    redactNames,
    sanitiseAsk,
    sanitiseTeam,
    groupByDay,
    formatDayLabel,
    latestLine,
    TEAMS,
    DEFAULT_TEAM,
    ROLE_ACCOUNT_WORDS,
    MODEL,
    MIN_COMMENTS_FOR_AI,
    MAX_DAYS_IN_SUMMARY,
    PROMPT_VERSION,
    ASK_KINDS,
};
