/**
 * constants.js
 * 
 * Constants for Data Kiosk API integration
 */

const MARKETPLACES = {
    US: 'ATVPDKIKX0DER',
    CA: 'A2EUQ1WTGCTBG2',
    MX: 'A1AM78C64UM0Y8',
    UK: 'A1F83G8C2ARO7P',
    DE: 'A1PA6795UKMFR9',
    FR: 'A13V1IB3VIYZZH',
    IT: 'APJ6JRA9NG5V4',
    ES: 'A1RKKUPIHCS9HS',
    JP: 'A1VC38T7YXB528',
    AU: 'A39IBJ37TRP1C6'
};

// Map regions to their default marketplaces
const REGION_DEFAULT_MARKETPLACES = {
    NA: 'US',    // North America defaults to US
    EU: 'UK',    // Europe defaults to UK
    FE: 'JP'     // Far East defaults to JP
};

// Valid marketplaces per region
const REGION_VALID_MARKETPLACES = {
    NA: ['US', 'CA', 'MX'],
    EU: ['UK', 'DE', 'FR', 'IT', 'ES'],
    FE: ['JP', 'AU']
};

const SCHEMA_NAMES = {
    SALES_AND_TRAFFIC: 'analytics_salesAndTraffic_2024_04_24',
    ECONOMICS: 'analytics_economics_2024_03_15',
    VENDOR_ANALYTICS: 'analytics_vendorAnalytics_2024_09_30'
};

const QUERY_STATUS = {
    IN_QUEUE: 'IN_QUEUE',
    IN_PROGRESS: 'IN_PROGRESS',
    DONE: 'DONE',
    FATAL: 'FATAL',
    CANCELLED: 'CANCELLED'
};

const FEE_TYPES = {
    FBA_FULFILLMENT_FEE: 'FBA_FULFILLMENT_FEE',
    FBA_STORAGE_FEE: 'FBA_STORAGE_FEE',
    REFERRAL_FEE: 'REFERRAL_FEE',
    PER_ITEM_SELLING_FEE: 'PER_ITEM_SELLING_FEE',
    AGED_INVENTORY_SURCHARGE: 'AGED_INVENTORY_SURCHARGE',
    BASE_FBA_FULFILLMENT_FEE: 'BASE_FBA_FULFILLMENT_FEE',
    BASE_MONTHLY_STORAGE_FEE: 'BASE_MONTHLY_STORAGE_FEE',
    CLOSING_FEES: 'CLOSING_FEES',
    FBA_FULFILLMENT_FEES: 'FBA_FULFILLMENT_FEES',
    HIGH_RETURN_RATE_FEE: 'HIGH_RETURN_RATE_FEE',
    LOW_INVENTORY_LEVEL_FEE: 'LOW_INVENTORY_LEVEL_FEE',
    MONTHLY_INVENTORY_STORAGE_FEES: 'MONTHLY_INVENTORY_STORAGE_FEES',
    PAN_EU_OVERSIZE_FEE: 'PAN_EU_OVERSIZE_FEE',
    RETURN_PROCESSING_FEE: 'RETURN_PROCESSING_FEE',
    SPONSORED_PRODUCTS_CHARGES: 'SPONSORED_PRODUCTS_CHARGES',
    STORAGE_UTILIZATION_SURCHARGE: 'STORAGE_UTILIZATION_SURCHARGE'
};

module.exports = {
    MARKETPLACES,
    REGION_DEFAULT_MARKETPLACES,
    REGION_VALID_MARKETPLACES,
    SCHEMA_NAMES,
    QUERY_STATUS,
    FEE_TYPES
};

